
# Garry's Mod weapons
gmod_camera=Câmera
gmod_tool=Arma de Ferramentas
manhack_welder=Arma de lâmina robô
weapon_fists=Punhos
weapon_flechettegun=Arma de dardos
weapon_medkit=Kit médico
weapon_physgun=Arma de Física

# Garry's Mod entities
edit_fog=Editor de neblina
edit_sky=Editor de céu
edit_sun=Editor de sol
sent_ball=Bola saltitante
gmod_balloon=Balão
gmod_button=Botão
gmod_cameraprop=Câmera
gmod_dynamite=Dinamite
gmod_emitter=Emissor
gmod_hoverball=Bola flutuante
gmod_lamp=Abajur
gmod_light=Luz
gmod_thruster=Propulsor
gmod_wheel=Roda
prop_effect=Efeito
ragdoll_motion=Controlador de Ragdoll

# Source Engine common entities
prop_physics=Física de objeto
prop_physics_multiplayer=Física de objeto
prop_physics_override=Física de objeto
prop_physics_respawnable=Física de objeto
simple_physics_prop=Física de objeto
physics_prop=Física de objeto
prop_ragdoll=Ragdoll
prop_ragdoll_attached=Ragdoll
physics_prop_ragdoll=Ragdoll

# Half-Life 2 weapons
weapon_357=Magnum 357
weapon_alyxgun=Arma da Alyx
weapon_annabelle=Annabelle
weapon_ar2=Espingarda de pulso
weapon_bugbait=Isca de inseto
weapon_citizenpackage=Ração alimentar
weapon_citizensuitcase=Mala
weapon_crossbow=Besta
weapon_crowbar=Pé de cabra
weapon_frag=Granada de fragmentação
weapon_physcannon=Arma de Gravidade
weapon_pistol=Pistola de 9MM
weapon_rpg=Lançador RPG
weapon_shotgun=Espingarda
weapon_slam=S.L.A.M.
weapon_smg1=Submetralhadora
weapon_stunstick=Bastão retrátil
weapon_oldmanharpoon=Arpão

# Half-Life 2 ammo
item_ammo_357=Caixa de Munição 357
item_ammo_357_large=Caixa de Munição 357 (Grande)
item_ammo_ar2=Pente de AR2
item_ammo_ar2_large=Pente de AR2 (Grande)
item_ammo_ar2_altfire=Munição de Orbe de Energia AR2
item_ammo_crossbow=Pacote de Balestra
item_ammo_pistol=Caixa De Munição de Pistola
item_ammo_pistol_large=Caixa de Munição de Pistola (Grande)
item_ammo_smg1=Caixa de Munição de Submetralhadora
item_ammo_smg1_large=Caixa de Munição de Submetralhadora (Grande)
item_ammo_smg1_grenade=Lançador de Granadas
item_ar2_grenade=Lançador de Granadas
item_box_buckshot=Caixa De Munição de Escopeta
item_flare_round=Cartucho de Sinalizador
item_box_lrounds=Caixa de Munição de AR2 (Pequena)
item_box_mrounds=Caixa de Munição de Submetralhadora (Pequena)
item_box_srounds=Caixa de Munição de Pistola (Pequena)
item_large_box_lrounds=Caixa de Munição de AR2 (Grande)
item_large_box_mrounds=Caixa de Munição de Submetralhadora (Grande)
item_large_box_srounds=Caixa de Munição de Pistola (Grande)
item_ml_grenade=Lançador de RPG
item_rpg_round=Lançador de RPG

# Half-Life 2 pickups
item_battery=Bateria de Traje
item_grubnugget=Pepita de comida
item_healthcharger=Carregador de Saúde
item_healthkit=Kit de Saúde
item_healthvial=Ampola de Vida
item_suit=Roupa H.E.V.
item_suitcharger=Carregador de Traje

# Half-Life 2 entities
combine_mine=Minério Combine
combine_mine_resistance=Mina de Resistência
prop_stickybomb=Dispositivo Magnusson
weapon_striderbuster=Dispositivo Magnusson
prop_thumper=Batedor
npc_grenade_frag=Granada vida
grenade_helicopter=Bomba de Helicóptero

# Half-Life 2 NPCs
npc_alyx=Alyx Vance
npc_antlion=Formiga-leão\n
npc_antlion_grub=Comida de Formiga-leão\n
npc_antlion_worker=Formiga-leão trabalhadora\n
npc_antlionguard=Guarda Formiga-leão\n
npc_antlionguardian=Guardiã Formiga-leão\n
npc_barnacle=Percevejo
npc_barney=Barney Calhoun
npc_breen=Wallace Breen
npc_citizen=Cidadão
npc_citizen_rebel=Rebelde
npc_citizen_medic=Médico Rebelde
npc_citizen_refugee=Refugiado
npc_citizen_rebel_enemy=Rebelde inimigo
npc_citizen_griggs=Griggs
npc_citizen_sheckley=Sheckley
npc_citizen_laszlo=Laszlo
npc_citizen_sandy=Sandy
npc_odessa=Odessa Cubbage
npc_clawscanner=Escaneador de Escudo
npc_combine_s=Soldado Combine
npc_combine_s_elite=Soldado de Elite Combine
npc_combine_s_shotgun=Soldado de Escopeta
npc_combine_s_prison=Guarda de Nova Prospekt
npc_combine_s_prison_shotgun=Guarda da prisão de Escopeta
npc_combinedropship=Nave de lançamento Combine
npc_combinegunship=Caça Combine
npc_combine_camera=Câmera do teto
npc_crow=Corvo
npc_cscanner=Escaner da Cidade
npc_dog=Cachorro
npc_eli=Eli Vance
npc_fisherman=Pescador
npc_gman=G-Man
npc_headcrab=Headcrab
npc_headcrab_black=Headcrab venenoso
npc_headcrab_fast=Headcrab veloz
npc_headcrab_poison=Headcrab Venenoso
npc_helicopter=Helicóptero de caça
npc_hunter=Caçador
npc_ichthyosaur=Ictiossauro\n
npc_kleiner=Dr. Isaac Kleiner
npc_magnusson=Dr. Arne Magnusson
npc_manhack=Manhack
npc_metropolice=Polícia do Metro
npc_monk=Reverendo Grigori
npc_mossman=Dr. Judith Mossman
npc_pigeon=Pombo
npc_rollermine=Rollermine
npc_rollermine_hacked=Rollermine hackeado
npc_rollermine_friendly=Rollermine inofensivo
npc_seagull=Gaivota
npc_sniper=Franco-atirador
npc_stalker=Perseguidor
npc_strider=Strider
npc_turret_ceiling=Sentinela de teto
npc_turret_floor=Sentinela Combine
npc_turret_floor_resistance=Sentinela da Resistência
npc_vortigaunt=Vortigaunt
npc_vortigaunt_slave=Escravo Vortigaunt
npc_vortigaunt_uriah=Uriah
npc_zombie=Zumbi
npc_zombie_torso=Torso de Zumbi
npc_fastzombie=Zumbi Rápido
npc_fastzombie_torso=Torso de Zumbi Rápido
npc_poisonzombie=Zumbi Venenoso
npc_zombine=Zumbine

# Half-Life: Source weapons
weapon_357_hl1=Pistola .357
weapon_crossbow_hl1=Besta vintage
weapon_crowbar_hl1=Pé de cabra vintage
weapon_egon=Arma Gluon
weapon_gauss=Canhão Tau
weapon_glock_hl1=Pistola 9mm (Glock)
weapon_hornetgun=Arma de Vespa
weapon_mp5_hl1=MP5
weapon_rpg_hl1=Lançador RPG vintage
weapon_satchel=Carga De Demolição
weapon_shotgun_hl1=Escopeta Spas-12
weapon_snark=Armadilhas
weapon_tripmine=Mina terrestre
weapon_handgrenade=Granada de mão

# Half-Life: Source ammo
ammo_357=Caixa de Munição 357
ammo_argrenades=Lançador de granada de MPG
ammo_mp5grenades=Lançador de granada de MPG
ammo_mp5clip=Carregador de MP5
ammo_9mmar=Carregador de MP5
ammo_9mmbox=Caixa de Munição 9mm
ammo_9mmclip=Pente de Glock
ammo_glockclip=Pente de Glock
ammo_buckshot=Caixa de Munição SPAS-12
ammo_crossbow=Pente de Besta
ammo_egonclip=Caixa de munição de Uranium
ammo_gaussclip=Caixa de munição de Uranium
ammo_rpgclip=Mísseis de RPG

# Half-Life: Source pickups
item_longjump=Módulo de Pulo Longo
weaponbox=Caixa de Armas

# Half-Life: Source NPCs
monster_alien_controller=Controlador alienígena
monster_alien_grunt=Grunido alienígena
monster_alien_slave=Vontigaunt Clássico
monster_babycrab=Headcrab bebê
monster_barnacle=Percevejo
monster_houndeye=Houndeye
monster_human_assassin=Assassino de operações especiais
monster_sentry=Sentinela
monster_human_grunt=Grunhido de H.E.C.U.
monster_ichthyosaur=Ictiossauro\n
monster_snark=Armadilha
monster_tentacle=Tentáculo
monster_zombie=Zumbi Clássico
monster_gman=G-Man
monster_gargantua=Gargantua
monster_turret=Sentinela pesada
monster_miniturret=Mini Sentinela
monster_nihilanth=Ninilanth
monster_scientist=Cientista
monster_sitting_scientist=Cientista
monster_barney=Agente de segurança
monster_bigmomma=Gonarch
monster_bullchicken=Bullsquid
monster_headcrab=Caranguejo clássico
monster_cockroach=Barata

# Half-Life: Source entities

# Portal entities
prop_energy_ball=Bala de alta energia
prop_glados_core=Núcleo de personalidade
prop_glados_core_curiosity=Núcleo de curiosidade
prop_glados_core_anger=Núcleo de raiva
prop_glados_core_crazy=Núcleo de inteligência
prop_glados_core_morality=Núcleo de moralidade

# Portal NPCs
npc_portal_turret_floor=Torreta sentinela
npc_rocket_turret=Torreta de foguetes
npc_security_camera=Câmera de segurança

# Half-Life 2 ammo
Pistol_ammo=Munição de pistola
357_ammo=Munição de Magnum 357
AlyxGun_ammo=Munição de Arma de Alyx
AR2_ammo=Munição de pulso
AR2AltFire_ammo=Bolas Combine
SMG1_ammo=Munição de Submetralhadora
SMG1_Grenade_ammo=Munição de Lançador de Granadas
Buckshot_ammo=Munição de escopeta
XBowBolt_ammo=Vareta de besta
RPG_Round_ammo=Munição de RPG
slam_ammo=Munição de S.L.A.M
Grenade_ammo=Granadas

# Half-Life: Source ammo
9mmRound_ammo=Munição 9mm
#12mmRound_ammo=12mm Ammo # Only used by NPCs
357Round_ammo=Munição de Pistola .357
GrenadeHL1_ammo=Granadas de mão
MP5_Grenade_ammo=Lançador de granada de MPG
BuckshotHL1_ammo=Munição de SPAS-12
XBowBoltHL1_ammo=Vareta de besta vintage
RPG_Rocket_ammo=Mísseis de RPG
Satchel_ammo=Carga para demolição
TripMine_ammo=Mina terrestre
Uranium_ammo=Urânio
Hornet_ammo=Ferrões
Snark_ammo=Armadilhas
