
spawnmenu.content_tab=Spawnlisten

spawnmenu.category.npcs=NPCs
spawnmenu.category.addons=Addons
spawnmenu.category.weapons=Waffen
spawnmenu.category.postprocess=Nachbearbeitung
spawnmenu.category.your_spawnlists=Deine Spawnlisten
spawnmenu.category.addon_spawnlists=Addon Spawnliste
spawnmenu.category.games=Spiele
spawnmenu.category.browse=Durchsuchen
spawnmenu.category.entities=Entities
spawnmenu.category.vehicles=Fahrzeuge
spawnmenu.category.creations=Kreationen
spawnmenu.category.dupes=Duplikationen
spawnmenu.category.saves=Spielst\u00e4nde

spawnmenu.tools_tab=Werkzeuge
spawnmenu.tools.constraints=Verbindungen
spawnmenu.tools.construction=Konstruktion
spawnmenu.tools.posing=Posieren
spawnmenu.tools.render=Darstellung
spawnmenu.tools.disabled=Dieses Tool ist vom Server deaktiviert\!

spawnmenu.menu.copy=In Zwischenablage kopieren
spawnmenu.menu.delete=L\u00f6schen
spawnmenu.menu.deletex=%i Objekte l\u00f6schen
spawnmenu.menu.edit=Bearbeiten
spawnmenu.menu.new=Neu
spawnmenu.menu.copy_dnd=Kopieren
spawnmenu.menu.move=Verschieben
spawnmenu.menu.new_category=Neue Kategorie
spawnmenu.menu.add_subcategory=Unterkategorie hinzuf\u00fcgen
spawnmenu.menu.edit_icon=Symbol bearbeiten
spawnmenu.menu.resize=Gr\u00f6\u00dfe ver\u00e4ndern
spawnmenu.menu.resizex=Gr\u00f6\u00dfe von &i Objekten ver\u00e4ndern
spawnmenu.menu.rerender=Neu rendern
spawnmenu.menu.rerenderx=%i Objekte erneut rendern
spawnmenu.menu.rerender_this=Dieses Symbol
spawnmenu.menu.rerender_all=Alle Symbole
spawnmenu.menu.spawn_with_toolgun=Mit der Toolgun spawnen
spawnmenu.menu.use_as_npc_gun=Als NPC Waffen\u00fcberschreibung verwenden
spawnmenu.menu.spawn_with_weapon=Mit Waffe spawnen

spawnmenu.savechanges=\u00c4nderungen speichern
spawnmenu.revert=Zur\u00fccksetzen
spawnmenu.revert_tooptip=\u00c4nderungen der Spawnliste zur\u00fccksetzen
spawnmenu.search=Suche...
spawnmenu.filter=Filter...
spawnmenu.quick_search=Schnellsuche...
spawnmenu.quick_search_tool=Schnellsuche\:
spawnmenu.quick_filter=Schnellfilter...
spawnmenu.quick_filter_tool=Schnellfilter\:
spawnmenu.enter_search=Zum suchen Enter dr\u00fccken
spawnmenu.press_search=Dr\u00fccken Sie, um zu suchen
spawnmenu.header_tooltip=Klicken und nach rechts ziehen um ein bearbeitbares Label in der Spawnliste abzulegen
spawnmenu.listname_tooltip=Der Name der ausgew\u00e4hlten Spawnliste
spawnmenu.newlabel=Neues Textlabel
spawnmenu.spawnlistnocontent=Die Spawnliste ben\u00f6tigt %s, welche nicht gemountet sind\!
spawnmenu.mountablegame=ein mountbares spiel
spawnmenu.createautospawnlist=Erstelle eine Spawnliste aus diesem Ordner
spawnmenu.openaddononworkshop=In Steam Workshop \u00f6ffnen
spawnmenu.mmb_weapons=Du kannst mit der mittleren Maustaste Waffen an deinem Fadenkreuz spawnen.

spawnmenu.utilities_tab=N\u00fctzliches
spawnmenu.utilities.user=Benutzer
spawnmenu.utilities.admin=Admin
spawnmenu.utilities.settings=Einstellungen
spawnmenu.utilities.cleanup=Aufr\u00e4umen
spawnmenu.utilities.cleanup.help=Eine Gruppe von Items entfernen.
spawnmenu.utilities.cleanup.all=Alles bereinigen
spawnmenu.utilities.undo=R\u00fcckg\u00e4ngig machen
spawnmenu.utilities.undo.help=Eine vorherige Aktion r\u00fcckg\u00e4ngig machen.
spawnmenu.utilities.physgunsettings=Physik-Gun Einstellungen
spawnmenu.utilities.sandbox_settings=Sandbox-Einstellungen
spawnmenu.utilities.server_settings=Server-Einstellungen

utilities.serversettings=Servereinstellungen. Diese Einstellungen k\u00f6nnen nur von der Person ge\u00e4ndert werden, die den Spielserver \u00fcber das Hauptmen\u00fc erstellt hat.
utilities.password=Server-Passwort\:
utilities.gravity=Gravitation\:
utilities.timescale=Physik Zeitskala\:
utilities.iterations=Physik Iterationen\:
utilities.kickerrornum=Bei clientseitigen Fehlern rauswerfen
utilities.allowcslua=Clientseitige Scripts erlauben
utilities.sticktoground=Auf dem Boden bleiben
utilities.sticktoground.help=Wenn aktiviert, werden die Spieler auf den Boden bleiben, wenn sie eine Rampe mit hoher Geschwindigkeit treffen. Wenn deaktiviert, werden die Spieler abprallen.
utilities.epickupallowed=Aufheben mit der BENUTZEN-Taste erlauben
utilities.falldamage=Realistischer Fallschaden
utilities.maxammo=Munitionslimit\:
utilities.maxammo.help=Erzwingt maximale Munitionsreserven f\u00fcr alle Waffen jedes Spielers. Werte von 0 und darunter bedeuten, dass stattdessen die maximale Munitionseinstellung des Waffentyps verwendet wird.
utilities.gmod_suit=HEV Suit-Funktionalit\u00e4t aktivieren
utilities.friction=Bodenreibung\:
utilities.deployspeed=Geschwindigkeit der Waffenplatzierung\:
utilities.noclipspeed=Noclip Geschwindigkeit\:
utilities.sv_timeout=Client Timeout\:
utilities.hostname=Servername\:
utilities.max_ragdolls=Maximale Ragdolls\:
utilities.max_ragdolls.help=Limits NPC corpses and prop gibs.

utilities.sandboxsettings=Sandbox-Einstellungen. Diese Einstellungen k\u00f6nnen nur von der Person ge\u00e4ndert werden, die den Server \u00fcber das Hauptmen\u00fc erstellt hat.
utilities.sandboxsettings_cl=Client-Sandbox Einstellungen. Diese wirken nur auf dein Spiel.
utilities.max_results=Maximale Suchergebnisse
utilities.max_results.help=Maximale Anzahl der Suchergebnisse, die die Spawnmen\u00fc-Suche anzeigen wird. Gr\u00f6\u00dfere Werte k\u00f6nnen die Leistung hindern.
utilities.mp_only=Die folgenden Einstellungen sind nur im Mehrspielermodus anwendbar.
utilities.spawnmenu_toggle=Spawn-Men\u00fc und Kontextmen\u00fc umschalten
utilities.spawnmenu_toggle.help=Das Spawn-Men\u00fc und das Kontextmen\u00fc werden beim Loslassen der Taste nicht geschlossen, wenn die Taste schnell angetippt wird. Zum Schlie\u00dfen erneut tippen.

utilities.physgunsettings=Clientseitige Physics Gun Einstellungen. Diese Einstellungen werden \u00fcber mehrere Sitzungen gespeichert.
utilities.gm_snapgrid=Gr\u00f6\u00dfe des Positionierungsrasters\:
utilities.gm_snapangles=Einrastwinkel\:
utilities.physgun_rotation_sensitivity=Rotationsempfindlichkeit\:
utilities.physgun_wheelspeed=Radgeschwindigkeit\:
utilities.physgun_drawbeams=Zeichne Physics Gun Beams
utilities.physgun_halo=Zeichne Physics Gun Objekt leuchten

utilities.physgunsvsettings=Serverseitige Physics Gun Einstellungen. Diese Einstellungen k\u00f6nnen nur von der Person ge\u00e4ndert werden, die den Server \u00fcber das Hauptmen\u00fc erstellt hat.
utilities.physgun_maxrange=Maximale Beam Reichweite\:
utilities.physgun_limited=Beschr\u00e4nke die Physics Gun
utilities.physgun_limited.help=Wenn diese Option aktiviert ist, kann die Physics Gun bestimmte Karten Entities nicht aufnehmen.
utilities.physgun_tpdist=Teleport Distanz\:
utilities.physgun_maxspeed=Maximale Objekt Geschwindigkeit\:
utilities.physgun_maxangular=Maximale Winkelgeschwindigkeit\:
utilities.physgun_timetoarrive=Zeit bis zur Ankunft\:
utilities.physgun_timetoarriveragdoll=Zeit bis zur Ankunft (Ragdoll)\:
utilities.physgun_timetoarriveragdoll.help=Zeit in Sekunden, die ein Ragdoll braucht, um dort anzukommen, wo die Physics Gun hinzeigt.

spawnmenu.searchindex=F\u00fcge installierte Modelle zur Spawnmen\u00fc-Suche hinzu...
spawnmenu.failedtofindmodels=F\u00fcr dieses Addon konnten keine Modelle gefunden werden.\nDies geschieht normalerweise, wenn mehrere Addons dieselben Modellpfade verwenden.

smwidget.icon_editor=Spawnsymbol Editor
smwidget.playermodel=Spielermodell
smwidget.playermodel_title=Spielermodellauswahl
smwidget.model=Modell
smwidget.colors=Farben
smwidget.color_plr=Spielerfarbe\:
smwidget.color_wep=Waffenfarbe\:
smwidget.bodygroups=K\u00f6rpergruppen
smwidget.animations=Animationen
smwidget.settings=Einstellungen

# DBinder
dbinder.none=KEINER
dbinder.press_a_key=DR\u00dcCKEN SIE EINE TASTE
dbinder.help=Linksklick zum \u00c4ndern\nRechtsklick zum L\u00f6schen\nMausradklick f\u00fcr Standard (falls verf\u00fcgbar)

KP_INS=Ziffernblock 0
KP_END=Ziffernblock 1
KP_DOWNARROW=Ziffernblock 2
KP_PGDN=Ziffernblock 3
KP_LEFTARROW=Ziffernblock 4
KP_5=Ziffernblock 5
KP_RIGHTARROW=Ziffernblock 6
KP_HOME=Ziffernblock 7
KP_UPARROW=Ziffernblock 8
KP_PGUP=Ziffernblock 9
KP_DEL=Ziffernblock .
KP_ENTER=Ziffernblock Enter
KP_PLUS=Ziffernblock +
KP_MINUS=Ziffernblock -
KP_SLASH=Ziffernblock /
KP_MULTIPLY=Ziffernblock *

# Vehicles
spawnmenu.vehicle.jeep=Jeep
spawnmenu.vehicle.airboat=Luftboot
spawnmenu.vehicle.jalopy=Jalopy
spawnmenu.vehicle.prisoner_pod=Gefangenen-Pod

spawnmenu.chair.wooden=Holzstuhl
spawnmenu.chair.office=B\u00fcrostuhl
spawnmenu.chair.office_big=Gro\u00dfer B\u00fcrostuhl
spawnmenu.chair.plastic=Plastikstuhl

spawnmenu.seat.jeep=Jeep-Sitz
spawnmenu.seat.jalopy=Jalopy-Sitz
spawnmenu.seat.airboat=Luftboot-Sitz
spawnmenu.seat.simple_sit=Autositz (Sit)
spawnmenu.seat.simple_jeep=Autositz (Jeep)
spawnmenu.seat.simple_airboat=Autositz (Luftboot)

# Spawnmenu entity categories
spawnmenu.category.fun_games=Spa\u00df + Spiele
spawnmenu.category.editors=Editor
spawnmenu.category.humans_resistance=Menschen + Widerstand
spawnmenu.category.zombies_aliens=Zombies + feindliche Aliens
spawnmenu.category.animals=Tiere
spawnmenu.category.combine=Combine
spawnmenu.category.chairs=St\u00fchle
spawnmenu.category.other=Sonstige

# Weapon selector & spawnmenu entity icon tooltips
entityinfo.author=Autor
entityinfo.contact=Kontakt
entityinfo.purpose=Zweck
entityinfo.instructions=Anweisungen

# Undo
undo.generic.npc=NPC
undo.generic.entity=Entit\u00e4t
undo.generic.weapon=Waffe
undo.generic.vehicle=Fahrzeug
undo.duplication=Duplikation
