
# Garry's Mod weapons
gmod_camera=카메라
gmod_tool=툴 건
manhack_welder=맨핵 건
weapon_fists=맨주먹
weapon_flechettegun=플레셰트 건
weapon_medkit=구급낭
weapon_physgun=피직스 건

# Garry's Mod entities
edit_fog=안개 편집기
edit_sky=스카이 에디터
edit_sun=선 에디터
sent_ball=바운시 볼
gmod_balloon=풍선
gmod_button=버튼
gmod_cameraprop=카메라
gmod_dynamite=다이나마이트
gmod_emitter=이미터
gmod_hoverball=호버볼
gmod_lamp=램프
gmod_light=불빛
gmod_thruster=추진기
gmod_wheel=바퀴
prop_effect=효과
ragdoll_motion=래그돌 컨트롤러

# Source Engine common entities
prop_physics=물리 프롭
prop_physics_multiplayer=물리 프롭
prop_physics_override=물리 프롭
prop_physics_respawnable=물리 프롭
simple_physics_prop=물리 프롭
physics_prop=물리 프롭
prop_ragdoll=래그돌
prop_ragdoll_attached=래그돌
physics_prop_ragdoll=래그돌

# Half-Life 2 weapons
weapon_357=.357 매그넘
weapon_alyxgun=알릭스 권총
weapon_annabelle=애너벨 소총
weapon_ar2=오버워치 표준 소총 (펄스-소총)
weapon_bugbait=페로포드 (벌레미끼)
weapon_citizenpackage=생존 보급품
weapon_citizensuitcase=여행 가방
weapon_crossbow=석궁
weapon_crowbar=크로우바
weapon_frag=수류탄
weapon_physcannon=영점 에너지 건 (중력건)
weapon_pistol=9MM 권총
weapon_rpg=RPG (로켓 추진 수류탄)
weapon_shotgun=산탄총
weapon_slam=S.L.A.M.
weapon_smg1=기관단총 (소형 기관총)
weapon_stunstick=전기 진압봉
weapon_oldmanharpoon=작살

# Half-Life 2 ammo
item_ammo_357=.357 탄약 상자
item_ammo_357_large=.357 탄약 상자 (대형)
item_ammo_ar2=AR2 탄창
item_ammo_ar2_large=AR2 탄창 (대형)
item_ammo_ar2_altfire=AR2 에너지 코어
item_ammo_crossbow=석궁 화살 묶음
item_ammo_pistol=권총 탄통
item_ammo_pistol_large=권총 탄통 (대형)
item_ammo_smg1=SMG 탄통
item_ammo_smg1_large=SMG 탄통 (대형)
item_ammo_smg1_grenade=SMG 유탄
item_ar2_grenade=SMG 유탄
item_box_buckshot=산탄총 탄약 상자
item_flare_round=플레어 탄약
item_box_lrounds=AR2 탄약 상자 (소형)
item_box_mrounds=SMG 탄약 상자(소형)
item_box_srounds=권총 탄약 상자(소형)
item_large_box_lrounds=AR2 탄약 상자 (대형)
item_large_box_mrounds=SMG 탄통 (대형)
item_large_box_srounds=권총 탄통 (대형)
item_ml_grenade=RPG 로켓
item_rpg_round=RPG 로켓

# Half-Life 2 pickups
item_battery=슈트 배터리
item_grubnugget=개미귀신 애벌레 덩어리
item_healthcharger=헬스 충전기
item_healthkit=헬스 키트
item_healthvial=헬스 바이알
item_suit=H.E.V. 슈트
item_suitcharger=슈트 차저

# Half-Life 2 entities
combine_mine=콤바인 지뢰
combine_mine_resistance=반시민군 지뢰
prop_stickybomb=매그너슨 장치
weapon_striderbuster=매그너슨 장치
prop_thumper=콤바인 진동기
npc_grenade_frag=활성화된 수류탄
grenade_helicopter=헬리콥터 폭탄

# Half-Life 2 NPCs
npc_alyx=알릭스 밴스
npc_antlion=개미귀신
npc_antlion_grub=개미귀신 애벌레
npc_antlion_worker=개미귀신 일꾼
npc_antlionguard=개미귀신 경비병
npc_antlionguardian=개미귀신 수호자
npc_barnacle=바나클
npc_barney=바니 칼훈
npc_breen=월리스 브린
npc_citizen=시민
npc_citizen_rebel=반시민군
npc_citizen_medic=반시민군 의무병
npc_citizen_refugee=난민
npc_citizen_rebel_enemy=적 반시민군
npc_citizen_griggs=그릭스
npc_citizen_sheckley=셰클리
npc_citizen_laszlo=라즐로
npc_citizen_sandy=샌디
npc_odessa=오데사 커비지
npc_clawscanner=실드 스캐너
npc_combine_s=콤바인 솔저
npc_combine_s_elite=콤바인 엘리트 솔저
npc_combine_s_shotgun=콤바인 산탄총병
npc_combine_s_prison=노바 프로스펙트 경비
npc_combine_s_prison_shotgun=노바 프로스펙트 산탄총 경비
npc_combinedropship=콤바인 드롭십
npc_combinegunship=콤바인 건십
npc_combine_camera=천장 카메라
npc_crow=까마귀
npc_cscanner=시티 스캐너
npc_dog=견
npc_eli=일라이 밴스
npc_fisherman=어부
npc_gman=G-맨
npc_headcrab=헤드크랩
npc_headcrab_black=포이즌 헤드크랩
npc_headcrab_fast=패스트 헤드크랩
npc_headcrab_poison=포이즌 헤드크랩
npc_helicopter=콤바인 공격 헬기
npc_hunter=헌터
npc_ichthyosaur=익시오서
npc_kleiner=아이작 클라이너 박사
npc_magnusson=어니 매그너슨 박사
npc_manhack=맨핵
npc_metropolice=시민 보호 기동대
npc_monk=그리고리 신부
npc_mossman=주디스 모스맨 박사
npc_pigeon=비둘기
npc_rollermine=롤러 마인
npc_rollermine_hacked=해킹된 롤러마인
npc_rollermine_friendly=무해한 롤러마인
npc_seagull=갈매기
npc_sniper=스나이퍼
npc_stalker=스토커
npc_strider=스트라이더
npc_turret_ceiling=천장 포탑
npc_turret_floor=콤바인 포탑
npc_turret_floor_resistance=반시민 포탑
npc_vortigaunt=보르티곤트
npc_vortigaunt_slave=보르티곤트 노예
npc_vortigaunt_uriah=유라이아
npc_zombie=좀비
npc_zombie_torso=좀비 몸통
npc_fastzombie=패스트 좀비
npc_fastzombie_torso=패스트 좀비 상체
npc_poisonzombie=포이즌 좀비
npc_zombine=좀바인

# Half-Life: Source weapons
weapon_357_hl1=.357 권총
weapon_crossbow_hl1=구식 석궁
weapon_crowbar_hl1=구식 크로우바
weapon_egon=글루온 건
weapon_gauss=타우 캐논
weapon_glock_hl1=9mm 권총 (글록)
weapon_hornetgun=호넷 건
weapon_mp5_hl1=MP5
weapon_rpg_hl1=구식 RPG 런처
weapon_satchel=가방 폭탄
weapon_shotgun_hl1=SPAS-12 산탄총
weapon_snark=스나크
weapon_tripmine=트립마인
weapon_handgrenade=수류탄

# Half-Life: Source ammo
ammo_357=.357 탄약 상자
ammo_argrenades=MP5 수류탄
ammo_mp5grenades=MP5 수류탄
ammo_mp5clip=MP5 탄창
ammo_9mmar=MP5 탄창
ammo_9mmbox=9mm 탄약 상자
ammo_9mmclip=글록 탄창
ammo_glockclip=글록 탄창
ammo_buckshot=SPAS-12 탄약 상자
ammo_crossbow=석궁 탄창
ammo_egonclip=우라늄 탄약 상자
ammo_gaussclip=우라늄 탄약 상자
ammo_rpgclip=RPG Rockets

# Half-Life: Source pickups
item_longjump=멀리뛰기 모듈
weaponbox=무기 상자

# Half-Life: Source NPCs
monster_alien_controller=외계인 컨트롤러
monster_alien_grunt=외계인 그런트
monster_alien_slave=클래식 보르티건트
monster_babycrab=헤드크랩 새끼
monster_barnacle=바나클
monster_houndeye=하운드아이
monster_human_assassin=블랙 옵스 어쌔신
monster_sentry=센트리 건
monster_human_grunt=H.E.C.U. 그런트
monster_ichthyosaur=익시오서
monster_snark=스나크
monster_tentacle=텐타클
monster_zombie=좀비
monster_gman=G-맨
monster_gargantua=가르강튀아
monster_turret=중포탑
monster_miniturret=미니 포탑
monster_nihilanth=니힐란스
monster_scientist=과학자
monster_sitting_scientist=과학자
monster_barney=보안 책임자
monster_bigmomma=고나크
monster_bullchicken=불스퀴드
monster_headcrab=클래식 헤드크랩
monster_cockroach=바퀴벌레

# Half-Life: Source entities

# Portal entities
prop_energy_ball=고에너지 펠릿
prop_glados_core=코어
prop_glados_core_curiosity=호기심 코어
prop_glados_core_anger=분노 코어
prop_glados_core_crazy=지능 코어
prop_glados_core_morality=윤리 코어

# Portal NPCs
npc_portal_turret_floor=터릿
npc_rocket_turret=로켓 터릿
npc_security_camera=보안 카메라

# Half-Life 2 ammo
Pistol_ammo=권총 탄약
357_ammo=.357 매그넘 탄약
AlyxGun_ammo=알릭스 건 탄약
AR2_ammo=펄스 소총 탄약
AR2AltFire_ammo=콤바인 공
SMG1_ammo=기관단총 탄약
SMG1_Grenade_ammo=기관단총 수류탄
Buckshot_ammo=산탄총 탄약
XBowBolt_ammo=석궁 화살
RPG_Round_ammo=RPG 라운드
slam_ammo=S.L.A.M. 탄약
Grenade_ammo=수류탄

# Half-Life: Source ammo
9mmRound_ammo=9mm 탄약
#12mmRound_ammo=12mm Ammo # Only used by NPCs
357Round_ammo=357 권총 탄약
GrenadeHL1_ammo=수류탄
MP5_Grenade_ammo=MP5 수류탄
BuckshotHL1_ammo=SPAS-12 탄약
XBowBoltHL1_ammo=구식 석궁 화살
RPG_Rocket_ammo=RPG Rockets
Satchel_ammo=가방 폭탄
TripMine_ammo=트립마인
Uranium_ammo=우라늄
Hornet_ammo=호넷
Snark_ammo=스나크
